#!/usr/bin/env bash
set -euo pipefail

REGION=${REGION:-australia-southeast1}
SUFFIX=${SUFFIX:-}
SERVICE="goblin-slackbot${SUFFIX}"

gcloud run deploy "$SERVICE" \
  --source . \
  --region "$REGION" \
  --port 8080 \
  --allow-unauthenticated \
  --set-env-vars \
OPENAI_API_KEY="${OPENAI_API_KEY?}",SLACK_BOT_TOKEN="${SLACK_BOT_TOKEN?}",SLACK_SIGNING_SECRET="${SLACK_SIGNING_SECRET?}",EXECUTOR_URL="${EXECUTOR_URL?}",AUTO_MAX_TRADE_SOL="${AUTO_MAX_TRADE_SOL:-0.25}",AUTO_MAX_STAKE_SOL="${AUTO_MAX_STAKE_SOL:-0.25}",ALLOWED_PROTOCOLS="${ALLOWED_PROTOCOLS:-jito}",ALLOWED_MINTS="${ALLOWED_MINTS:-SOL,USDC,JITOSOL,BONK}",PRICE_IMPACT_MAX_PCT="${PRICE_IMPACT_MAX_PCT:-2}",SECRET_APPROVAL_KEY="${SECRET_APPROVAL_KEY:-dev}"

