name: Canary

on:
  schedule:
    - cron: '*/15 * * * *'
  workflow_dispatch:

jobs:
  canary:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run canary checks
        env:
          EXECUTOR_URL: ${{ secrets.EXECUTOR_URL }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          bash scripts/canary.sh


