name: CI

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Authenticate to GCP (optional)
        if: ${{ secrets.GCP_WIF_PROVIDER != '' && secrets.GCP_WIF_SERVICE_ACCOUNT != '' }}
        uses: google-github-actions/auth@v2
        with:
          token_format: access_token
          workload_identity_provider: ${{ secrets.GCP_WIF_PROVIDER }}
          service_account: ${{ secrets.GCP_WIF_SERVICE_ACCOUNT }}
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          pip install pytest
      - name: Run tests
        run: |
          pytest -q

name: CI (solana agent scaffold)
on:
  pull_request:
  push:
    branches: [ main ]
jobs:
  scaffold-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Ensure scaffold exists
        run: |
          test -d src
          test -d tests
          test -f README.md
          test -f docs/OVERVIEW.md
          test -f docs/ARCHITECTURE.md
          test -f docs/CAPABILITIES.md
          test -f docs/SAFETY.md
          test -f ops/RUNBOOK.md
