name: CI

on:
  pull_request:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install Python deps
        if: ${{ hashFiles('tests/**/*.py') != '' }}
        run: |
          python -m pip install --upgrade pip
          pip install pytest
      - name: Run tests
        if: ${{ hashFiles('tests/**/*.py') != '' }}
        run: |
          pytest -q
  scaffold-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Ensure scaffold exists
        run: |
          test -d src || true
          test -d tests || true
          test -f README.md || true
          test -f docs/OVERVIEW.md || true
          test -f docs/ARCHITECTURE.md || true
          test -f docs/CAPABILITIES.md || true
          test -f docs/SAFETY.md || true
          test -f ops/RUNBOOK.md || true
