name: Staging Deploy and Smoke Tests

on:
  push:
    branches: [ main ]
  workflow_dispatch:

concurrency:
  group: stg-${{ github.ref }}
  cancel-in-progress: false

jobs:
  deploy-staging:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Detect auth mode
        env:
          JSON1: ${{ secrets.GCP_SA_KEY }}
          JSON2: ${{ secrets.GOOGLE_CLOUD_CREDENTIALS }}
        run: |
          if [ -n "${JSON1}${JSON2}" ]; then
            echo "HAS_JSON=true" >> $GITHUB_ENV
          else
            echo "HAS_JSON=false" >> $GITHUB_ENV
          fi
      - name: Auth (JSON credentials)
        if: env.HAS_JSON == 'true'
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY != '' && secrets.GCP_SA_KEY || secrets.GOOGLE_CLOUD_CREDENTIALS }}
      - name: Auth (Workload Identity Federation)
        if: env.HAS_JSON != 'true'
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WIF_PROVIDER }}
          service_account: ${{ secrets.GCP_WIF_SERVICE_ACCOUNT }}
      - name: Set up gcloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
      - name: Install jq
        run: |
          sudo apt-get update
          sudo apt-get install -y jq
      - name: Deploy staging
        run: |
          chmod +x scripts/deploy-staging.sh
          ./scripts/deploy-staging.sh
        env:
          OPENAI_PROJECT: ${{ secrets.OPENAI_PROJECT }}
          EXECUTOR_URL: ${{ secrets.EXECUTOR_URL }}
          EXECUTOR_TOKEN: ${{ secrets.EXECUTOR_TOKEN }}
          WALLET_ADDRESS: ${{ secrets.WALLET_ADDRESS }}
          ALLOWED_TELEGRAM_USER_IDS: ${{ secrets.ALLOWED_TELEGRAM_USER_IDS }}
          PLANNER_TIMEOUT_SEC: 8
          SECRET_OPENAI: openai-api-key-stg
          SECRET_TELEGRAM: telegram-bot-token-stg
          SECRET_WEBHOOK: telegram-webhook-secret-stg
      - name: Resolve staging URL
        id: url
        run: |
          URL=$(gcloud run services describe telegram-service-stg --region australia-southeast1 --format='value(status.url)')
          echo "url=$URL" >> $GITHUB_OUTPUT
      - name: Smoke - port/health
        run: |
          curl -sSfL ${{ steps.url.outputs.url }} >/dev/null || (echo "Home failed" && exit 1)
      - name: Smoke - getMe (Telegram)
        run: |
          curl -sSfL "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/getMe" | jq .ok | grep true
      - name: Smoke - webhook reconcile
        run: |
          echo "Webhook will be reconciled by app on start; verifying URL…"
          set -e
          INFO=$(curl -s "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/getWebhookInfo")
          echo "$INFO" | jq .ok | grep true
      - name: Emoji snapshot test (static)
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          pytest tests/test_emoji_patterns.py -q


